"""Session-token primitives and email-to-user_key mapping.

Provides the small, dependency-free helpers used by the OAuth callback and the
session middleware: opaque URL-safe token generation, the SHA-256 hashing used
as the storage key in the ``sessions`` table, and the single-user mapping from
authenticated email to the internal ``user_key`` that scopes all data rows.

Sits below the auth middleware and the sessions repository; it owns no I/O and
holds no state.
"""

from __future__ import annotations

import base64
import hashlib
import secrets

from pulse_server.config import get_settings


def generate_token(*, num_bytes: int) -> str:
    """Generate a URL-safe random session token of the requested byte length.

    **Inputs:**
    - num_bytes (int): Number of random bytes to draw before base64url encoding.

    **Outputs:**
    - str: Base64url-encoded token without padding (32 bytes -> 43 chars).
    """
    raw = secrets.token_bytes(num_bytes)
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def hash_token(token: str) -> bytes:
    """Compute the SHA-256 digest of a UTF-8-encoded session token.

    Also used to hash the short-lived OAuth exchange code before storage so a
    database leak does not expose live codes.

    **Inputs:**
    - token (str): Opaque session token (or exchange code) issued to the client.

    **Outputs:**
    - bytes: 32-byte SHA-256 digest suitable for storage as a table PK.
    """
    return hashlib.sha256(token.encode("utf-8")).digest()


def pkce_s256_challenge(code_verifier: str) -> str:
    """Derive the RFC 7636 S256 code challenge for a PKCE verifier.

    **Inputs:**
    - code_verifier (str): The high-entropy verifier generated by the client.

    **Outputs:**
    - str: Base64url-encoded (no padding) SHA-256 digest of the verifier.
    """
    digest = hashlib.sha256(code_verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def verify_pkce_s256(code_verifier: str, code_challenge: str) -> bool:
    """Check that a PKCE verifier matches the stored S256 challenge.

    Uses a constant-time comparison to avoid leaking match progress. A verifier
    containing non-ASCII characters (an RFC 7636 verifier is ASCII-only) cannot
    match any valid challenge, so it is treated as a mismatch rather than raising
    — callers map a ``False`` result to a 400, never a 500.

    **Inputs:**
    - code_verifier (str): Verifier presented by the client at exchange time.
    - code_challenge (str): Challenge captured at authorize time.

    **Outputs:**
    - bool: ``True`` when ``S256(code_verifier) == code_challenge``.
    """
    try:
        expected = pkce_s256_challenge(code_verifier)
    except UnicodeEncodeError:
        return False
    return secrets.compare_digest(expected, code_challenge)


def email_to_user_key(email: str) -> str:
    """Map an authenticated email to the ``user_key`` used for data scoping.

    Single-user today: returns the configured ``legacy_user_key`` regardless of
    the input email. Multi-user mapping will be introduced later.

    **Inputs:**
    - email (str): Authenticated email address from the verified Google ID token.

    **Outputs:**
    - str: The configured ``legacy_user_key``.
    """
    del email
    return get_settings().legacy_user_key
